# Generated by Django 4.2 on 2023-05-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
